<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
        <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2"/>
        <PackageReference Include="NSubstitute" Version="6.2.0"/>
        <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0"/>
        <PackageReference Include="Serilog.Sinks.InMemory" Version="2.0.0"/>
        <PackageReference Include="xunit.v3" Version="4.0.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Fanstatic\Fanstatic.csproj"/>
    </ItemGroup>

</Project>
