using System;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Fanstatic.Generator;

[Generator(LanguageNames.CSharp)]
public class FanstaticGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            var buildDate = DateTime.UtcNow;
            var source = $@"// <auto-generated />
#nullable enable

using System;

namespace Fanstatic.Models
{{
    public static partial class FanstaticExt
    {{
        private static partial DateTime _BuildDate() => new DateTime({buildDate.Ticks}L, DateTimeKind.Utc);
        private static partial long _BuildDateTicks() => {buildDate.Ticks}L;
    }}
}}
";
            ctx.AddSource("FanstaticExt.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }
}
